# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ilker Cakir Website
email: cakir.ilker@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  A personel blog site created with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cakirilker.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iIkercakir
github_username: cakirilker
linkedin_username: cakirilker

# Build settings
markdown: kramdown
plugins:
  - jekyll
  - jekyll-feed
  - jekyll-paginate
  - minima
  - tzinfo-data
  - jekyll-assets
  - coffee-script
  - uglifier
  - sass
  - jekyll-sitemap
encoding: utf-8
collections:
  - experiences
permalink: /blog/:year/:month/:title

# Pagination Settings
paginate: 2
paginate_path: "/blog/page:num/"

# Custom Variables
blog:
  url: https://blog.cakirilker.com/

defaults:
  - scope:
      path: "assets/**/*"
    values:
      sitemap: false
